### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by PietroFalcetti** [bostrom/text-to-image#155] opened 2021-07-01 13:30 UTC
Hello,

I need to use a transparent background for the image, but when setting 'transparent' as bgColor, it works correctly, but it shows 2 texts, as you can see in the attach.

If I use any other color as bgColor, it works correctly.

Transparent bg, with 2 texts.

![Sign](https://user-images.githubusercontent.com/45390137/124132322-fc63cc80-da80-11eb-896b-e49476427bed.png)

Red bg, with 1 text.
![Sign](https://user-images.githubusercontent.com/45390137/124132452-20271280-da81-11eb-9f73-c08d03bdd776.png)

How can i solve it ? 

Thanks in advance.

EDIT: 

Solved by applying margin 0 in the config object.

**Comment by cedricsandars** [comment] 2021-07-17 21:36
@bostrom  - This issue still exists in the latest version. I think this is happening only when bgColor is transparent and when we apply customHeight.

**Comment by majweb** [comment] 2024-10-28 07:20
The problem is I still have version 7.0. And if I add transparent or rgba(255,255,255,0) in bgColor, the texts overlap.
![chrome_c4CXr9nIQS](https://github.com/user-attachments/assets/17556144-9f99-482a-92dc-2abf5beed0db)

**Comment by bostrom** [comment] 2024-10-28 09:17
@majweb can you reproduce this in a codesandbox and share it?

**Comment by majweb** [comment] 2024-10-29 07:12
I have a big enough project to handle it in codesandbox. In short, everything works fine, but if I add bgColor:'transparent' there is a problem.

Easy flow:
const textToPad = ref('');

const addTextToPad = async () => {
    if(textToPad){
        const dataUri = await generate(textToPad.value,{
            fontSize: size.value,
            bgColor:'transparent',
            customHeight:150,
            margin:0,
            lineHeight:45,
            fontFamily: font.value,
            textColor: 'black',
            textAlign: 'center',
            verticalAlign: 'center',
        });
        signaturePad.value && signaturePad.value.fromDataURL(dataUri);
    }
}

watch(textToPad, () => {
    addTextToPad();
});


<input type="text"  v-model="textToPad" placeholder="text to canvas"  id="textToPad" maxlength="40"/>

**Comment by bostrom** [comment] 2024-10-29 19:03
@majweb I added your transparent background example to the [examples sandbox](https://codesandbox.io/p/sandbox/gtcmdy) and it renders fine. 

Could the issue be with the final rendering of the image in your application? Seems that you're getting multiple images on top of each other as you type and the image updates?

**Comment by bostrom** [comment] 2024-10-31 16:34
I'm closing this as transparent background works in my example. Let's reopen if someone proves me wrong.

**Closed by bostrom** 2024-10-31 16:34 UTC

**Comment by majweb** [comment] 2024-12-16 12:23
the images overlap but why?
